### ISSUE TITLE
Add CLI bolt support for downloading artifacts

### ISSUE THREAD

**Issue by adamcunnington-mlg** [paradime-io/paradime-python-sdk#17]
Please add a `paradime bolt` subcommand for downloading artifacts. I only need `manifest.json` right now so I'm using `p.bolt.get_latest_manifest_json` but probably makes sense for the artifact to be a CLI option with default value.

The reason for asking for this is so we can invoke this common operation via simple CLI call rather than having to execute python code. Our calling context is a `Makefile` so this simplifies our implementation significantly.

**Comment by bhuvansingla** [comment]
Hey @adamcunnington-mlg! Thanks a lot for raising the issue. I have now released a new [version](https://github.com/paradime-io/paradime-python-sdk/releases/tag/4.6.0) that supports the suggested CLI command 🚀. You can look at the description of this pull request to know more: https://github.com/paradime-io/paradime-python-sdk/pull/18.

**Comment by adamcunnington-mlg** [comment]
Awesome! Works great, thanks
